language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - ENVIRONMENT=test
    - VERBOSE=true

install:
  - sudo $TRAVIS_BUILD_DIR/ci/scripts/install.sh
  - VENVDIR=$VIRTUAL_ENV make install

script:
  - VENVDIR=$VIRTUAL_ENV make test

after_success:
  - VENVDIR=$VIRTUAL_ENV make coverage